Traceback (most recent call last):
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WAI\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\WAI\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# js2pyÎ°ú ÏûêÎ∞îÏä§ÌÅ¨Î¶ΩÌä∏ ÏΩîÎìú ÌôïÏù∏
import js2py

js_code = """
function solution(arr){
    var answer = [];
    for(var i = 0;i<arr.length;i++){
        if(answer.slice(-1)[0]!=arr[i]){
            answer.push(arr[i]);
        }
    }
    return answer;
}
"""
my_code = js2py.eval_js(js_code)
my_code(arr)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[4], line 2[0m
[0;32m      1[0m [38;5;66;03m# js2pyÎ°ú ÏûêÎ∞îÏä§ÌÅ¨Î¶ΩÌä∏ ÏΩîÎìú ÌôïÏù∏[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mjs2py[39;00m
[0;32m      4[0m js_code [38;5;241m=[39m [38;5;124m"""[39m
[0;32m      5[0m [38;5;124mfunction solution(arr)[39m[38;5;124m{[39m
[0;32m      6[0m [38;5;124m    var answer = [];[39m
[1;32m   (...)[0m
[0;32m     13[0m [38;5;124m}[39m
[0;32m     14[0m [38;5;124m"""[39m
[0;32m     15[0m my_code [38;5;241m=[39m js2py[38;5;241m.[39meval_js(js_code)

[1;31mModuleNotFoundError[0m: No module named 'js2py'

